# Generated by Django 5.2.1 on 2025-05-29 14:33

from django.db import migrations
from wine_wiki.wine_list_categories import subcategories, wine_list_categories


def add_wine_list_categories(apps, schema_editor):
    WineListCategory = apps.get_model("wine_wiki", "WineListCategory")

    for order, category in wine_list_categories:
        winelistcategory = WineListCategory(order=order, category=category)
        winelistcategory.save()


def add_wine_list_subcategories(apps, schema_editor):
    WineListSubCat = apps.get_model("wine_wiki", "WineListSubCat")
    WineListCategory = apps.get_model("wine_wiki", "WineListCategory")

    for winelistcategory_pk, order, category in subcategories:
        winelistsubcat = WineListSubCat(
            winelistcategory_pk=WineListCategory.objects.get(pk=winelistcategory_pk),
            order=order,
            subcategory=category,
        )

        winelistsubcat.save()


class Migration(migrations.Migration):
    dependencies = [
        ("wine_wiki", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_wine_list_categories),
        migrations.RunPython(add_wine_list_subcategories),
    ]
