# Generated by Django 5.2.1 on 2025-05-29 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer_name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Description of the producer')),
            ],
        ),
        migrations.CreateModel(
            name='WineListCategory',
            fields=[
                ('order', models.IntegerField()),
                ('category', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WineListSubCat',
            fields=[
                ('order', models.IntegerField()),
                ('subcategory', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('winelistcategory_pk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wine_wiki.winelistcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine_name', models.CharField(max_length=100)),
                ('vintage', models.CharField(max_length=4)),
                ('region', models.CharField(max_length=100)),
                ('subregion', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('is_published', models.BooleanField(default=False, verbose_name='Publish?')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('bpos_key', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(help_text='Formatted using ReST')),
                ('winelistcategory_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wine_wiki.winelistcategory')),
                ('winelistsubcat_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wine_wiki.winelistsubcat')),
            ],
        ),
    ]
