# Generated by Django 5.2.1 on 2025-05-29 15:27

from django.db import migrations
from wine_wiki.sample_wine_data import sample_data


def add_sample_wines(apps, schema_editor):
    Wine = apps.get_model("wine_wiki", "Wine")
    WineListSubCat = apps.get_model("wine_wiki", "WineListSubCat")
    WineListCategory = apps.get_model("wine_wiki", "WineListCategory")

    for wine in sample_data:
        winelistcategory_pk = wine.pop("winelistcategory_pk")
        winelistsubcat_pk = wine.pop("winelistsubcat_pk")

        try:
            wine = Wine(
                winelistcategory_pk=WineListCategory.objects.get(
                    pk=winelistcategory_pk
                ),
                winelistsubcat_pk=WineListSubCat.objects.get(pk=winelistsubcat_pk),
                **wine,
            )
        except Exception as e:
            breakpoint()
            raise e

        wine.save()


class Migration(migrations.Migration):
    dependencies = [
        ("wine_wiki", "0003_remove_wine_slug"),
    ]

    operations = [migrations.RunPython(add_sample_wines)]
