# Generated by Django 5.2.1 on 2025-06-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0004_ingest_sample_wines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='bpos_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='wine',
            name='description',
            field=models.TextField(blank=True, help_text='Formatted using ReST'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='subregion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='wine',
            name='wine_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
